CREATE DATABASE PROJETOA3;
USE PROJETOA3;

CREATE TABLE Cliente(
    id INT PRIMARY KEY AUTO_INCREMENt,
    nome VARCHAR(255),
    cpf VARCHAR(11)
);

CREATE TABLE Produto (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    categoria VARCHAR(255),
    preco DOUBLE,
    quantDeEstoque INT
);

CREATE TABLE Funcionario(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    cpf VARCHAR(11)
);

SELECT * FROM Cliente;
SELECT * FROM Produto;
SELECT * FROM Funcionario;
